# 服を盗めるプレイヤー
thief:
  - dev1
  - dev2
  - dev3

# 服を盗まれるプレイヤー
target:
  - torareru1
  - torareru2
  - torareru3

# 一発ですべての服が脱げるプレイヤー
oneshots:
  - ippatu1
  - ippatu2
  - ippatu3

#特別設定
#選択可能アイテムタイプ: CHESTPLATE, LEGGINGS, BOOTS
#選択可能アイテム素材: LEATHER, GOLD, CHAIN, DIAMOND
#色指定方法: #114514 <= 16進数指定, シャープ必ずつける
#文字色指定方法: §<数字>  https://minecraft-ja.gamepedia.com/装飾コード 参照
#環境変数一覧：
#    - %%name%%       = ターゲットの名前
#    - %%armor_type%% = 服の種類
#    - %%material%%   = 服の素材
specials:
  - name: torareru1
    itemName: "§6つよそうな§b%%armor_type%%"
  - name: torareru2
    items:
      - type: CHESTPLATE
        name: "とられる2の§bかわいいふく！"
      - type: CHESTPLATE
        name: "とられる2の§bかわいいぱんつ！"
      - type: BOOTS
        name: "とられる2の§bかわいいくつ！"
  - name: torarery3
    items:
      - type: LEGGINGS
        name: "§6%%name%%の§b%%armor_type%%"
        effect:
          particle: SPELL_MOB_AMBIENT
          count: 10
          offsetX: 0.1
          offsetY: 0.3
          offsetZ: 0.1
          extra: 0.1


#レアなアイテム
rares:
  - chance: 50 #50回に1回
    item:
      name: "§6%%name%%§bの水着"
      material: LEATHER
      type: CHESTPLATE
      color: "#282f5b"
  - chance: 100
    item:
      name: "2年2組 ぺやんぐ(水着)"
      material: LEATHER
      type: CHESTPLATE
      color: "#282f5b"

# 服が回復するまでの時間(秒)
heal: 60
# エフェクト出すタイマー(チック)
effect: 10

# スキン
# orderの最大値は３で、０：全身服を着たスキン、１：くつだけを脱いだスキン、２：くつと上着だけ脱いだスキン、３：全裸のスキン
# 上のheal時間ごとに-1されたorderのスキンに変わり、最終的に０のスキンとなります。
skins:
  # かきかた
  #- order: 0
  #  value: <テクスチャ>
  #  signature: <シグネチャ>
