#シフト右クリックの対象にデキる人
target:
  - SaikyouPeyangsan
  - YukiAt

#盗める人
thief:
  - SaikyouPeyangsan
  - YukiAt

#特別設定
#選択可能アイテムタイプ: HELMET, CHESTPLATE, LEGGINGS, BOOTS
#色指定方法: #114514 <= 16進数指定, シャープ必ずつける
specials:
  - name: YOSHIKO__chan__
    items:
      - type: LEGGINGS
        name: "膝のあたりが臭いよしこのズボン"
  - name: ikeko_99
    items:
      - type: HELMET
        name: "いけこのエッチな帽子"
        # color: "#000000"
      - type: CHESTPLATE
        name: "いけこのエッチな上着"
        # color: "#000000"
      - type: LEGGINGS
        name: "いけこのエッチなズボン"
        # color: "#000000"
      - type: BOOTS
        name: "いけこのエッチなヒール"
        # color: "#000000"

#ランダムで選択されるスキン
skins:
  - name: "skinA"
    value: "ewogICJ0aW1lc3RhbXAiIDogMTYxMDMwNzc5NzM4NiwKICAicHJvZmlsZUlkIiA6ICJiNzQ3OWJhZTI5YzQ0YjIzYmE1NjI4MzM3OGYwZTNjNiIsCiAgInByb2ZpbGVOYW1lIiA6ICJTeWxlZXgiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjc1MzQ1MzM0NWRjNzY1MmVjZTBiNzc4Mjc2OGVkMmY2Zjg4NjNhOWU1MzUyMDFhODUzNTUyMjBmOWY5MjBjIgogICAgfQogIH0KfQ=="
    signature: "kyPGlJ1i3wTBBvMnoNRze73wgf2ylxLWIzHEJhs7bugFrtWX+3bJdgfN/tC5s3dDMJ6yIcgjvVu7utkILC0M0Q9vYPjDrm1w3I/FmOWeQ64Q1hlmISk7AgAG2JaSS9EzLSVlvJLvdPogdgHwHe0dDkV31a1WCWUpBRDhYcYSj3oMgD6aw9Y03XVScsYzMZKZQG+GKD1EwY0RM0xvDLDmO3FVPDYCqpxzut3JEV/o6kL2XEvYa5H+5iEOuBcKoVnBDaUMIHExAoRtnfyNzZIfc2wK+ytHn1pY7vZPdHsEbKAXIxb8w93S/rFhPOzGzujOa0e+s6VqyfCsjRhHBp+Xj1COlQqAhObOS4shtzTs4vFsZKtDm+bQrHegCuEIflh2+ChqQ92BY+FbHz1La0OiyXmuGeqeSh9aSgr8Qxp5fS80IHVA9JLgRCG8mRY14c+Hwc08+ZE7l6RHLSRQtdU2cZUBqxw4RRCek+00q6kXyhIN2BMtN8zl6GD0t7JZG6F475FoisLnZpnsmEoW+mvkwzpKIg0SmZAs7nFpd9t9dSYhE/E36M+ccWoywXGoN6v3mAMcgO+iY2J7aq+wswNWx/jZi5vKxKP9tN3OXCEn/7D3uNDmLZy30YTtM+u2AVT8pqAeo1Mr3BWaWQfeRkAaxyjUZC9F0GCAcJHmLRqyXac="
  - name: "skinB"
    value: "ewogICJ0aW1lc3RhbXAiIDogMTYxMDMwNzcwOTg1MywKICAicHJvZmlsZUlkIiA6ICI5ZDQyNWFiOGFmZjg0MGU1OWM3NzUzZjc5Mjg5YjMyZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJUb21wa2luNDIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjdkZmFkNTZiMmQzNGM3NThlNmIxYzNiMTA2NzYwNjkwMWZiNDU0ODhjODgzOWE0YzU1ZWNlMGY0ZjYyYTJlMiIKICAgIH0KICB9Cn0="
    signature: "I2cD3Zhfg4E/LrOca+ETn9zEh2K0vfo5Ch0GXQbRqOh6kDXylhZU8nrJZ5I06S6fH9Tc8bN4Ext8Wr4+pWo6zhKw8OXdXPhOVu8J+EUwznQ7LrpHoy3I1qc/dIQGX92WumhKWr1MZrde13hxwjsJFfAUTSGgVHOzJGXFc/8qa658WKlhlPQ6FwdTAYDJ4ySNjJX8OQPytirUXHaTPhGg4jPHTdh0XQpoAv1+AZVbdAwe3cMIjmfq8nXVJXblHgqU6k2Xxb19VMoWqlfBT6xnxc3akb0KDVlvwxrw8Qwy3WAQBiJG6YAduSDd73D+9+XTSytpmSxK6xP3ul03leQDf9/yK0M9LIF9T6Z5+Qow6sMEqdpqXHmGjQNbV40ekGk3ztHsH2aGNIVpFhHeTLUbAJApwyARhdyiXhzb/+aTw2UGqxrdwbIFT/pDJ/sHfmM8cPcfVIJko4V43nhGvkOpM1m+3KGv12oZKUEOGxBcRFQK/H0eR0L56gsyaaR8HowVstN1Pqh4wIVaOF4yctnO+4p6Z3vRO6LZh825x5H+pyt82/o4w6J308wfWu8Eeg9dddieZEzkexC4b7gJD224JvEIiAQW7EqwDWYG+Pa916HVJtaFyB8TPmF/OjtL53B0xhRxx3EvY05GLwpW6L0Dd++w4Sk/FkrxAIqAirPA4qQ="

#プレイヤーに固有のスキンをもたせる(同じプレイヤは同じスキンにしか変化しない
same: true